#!/bin/bash

# Handy little script for building an offical version. This is useful
# if you want libpdf.so with your chromium build. Since libpdf.so is
# proprietary, it needs to be extracted from Google Chrome, and often
# times, you need a matching Google Chrome and Chromium version.

CHANNEL=${CHANNEL:-stable}
LIBPDF=${LIBPDF:-yes}

if [ "$CHANNEL" = "dev" ]; then
  CHANNEL=unstable
fi

if [ "$(uname -m)" = "x86_64" ]; then
  DARCH=amd64
else
  DARCH=i386
fi

case "$CHANNEL" in
  stable)
    wget http://dl.google.com/linux/direct/google-chrome-stable_current_${DARCH}.deb
    ;;
  beta)
    wget http://dl.google.com/linux/direct/google-chrome-beta_current_${DARCH}.deb
    ;;
  unstable)
    wget http://dl.google.com/linux/direct/google-chrome-unstable_current_${DARCH}.deb
    ;;
  *)
    echo $CHANNEL is not a valid channel
    exit 1
    ;;
esac

# http://slackbuilds.org/slackbuilds/13.0/network/google-chrome/google-chrome.SlackBuild
VERSION=$(ar p google-chrome-${CHANNEL}_current_${DARCH}.deb control.tar.gz | tar zxO ./control | grep Version | awk '{print $2}' | cut -d- -f1)

if [ "$LIBPDF" = "yes" ]; then
  ar p google-chrome-${CHANNEL}_current_${DARCH}.deb data.tar.lzma | lzma -cd | tar xO ./opt/google/chrome/libpdf.so > libpdf.so
fi

if [ ! -e chromium-${VERSION}.tar.bz2 ]; then
  echo Downloading chromium-${VERSION}.tar.bz2...
  sleep 2
  wget http://build.chromium.org/official/chromium-${VERSION}.tar.bz2
fi

echo Running chromium.SlackBuild...
sleep 2
bash chromium.SlackBuild
