#!/bin/bash

# Handy little script for building an offical version. This is useful
# if you want libpdf.so with your chromium build. Since libpdf.so is
# proprietary, it needs to be extracted from Google Chrome, and often
# times, you need a matching Google Chrome and Chromium version.

CHANNEL=${CHANNEL:-stable}
LIBPDF=${LIBPDF:-yes}

if [ "$CHANNEL" = "dev" ]; then
  CHANNEL=unstable
fi

if [ "$(uname -m)" = "x86_64" ]; then
  DARCH=amd64
else
  DARCH=i386
fi

set -e

DEB="google-chrome-${CHANNEL}_current_${DARCH}.deb"
if [ ! -e "$DEB" ]; then
  wget http://dl.google.com/linux/direct/$DEB
fi

# http://slackbuilds.org/slackbuilds/13.0/network/google-chrome/google-chrome.SlackBuild
VERSION=$(ar p $DEB control.tar.gz | tar zxO ./control | grep Version | awk '{print $2}' | cut -d- -f1)

if [ "$LIBPDF" = "yes" ]; then
  ar p $DEB data.tar.lzma | lzma -cd | tar xO ./opt/google/chrome/libpdf.so > libpdf.so
fi

if [ ! -e chromium-${VERSION}.tar.bz2 ]; then
  echo Downloading chromium-${VERSION}.tar.bz2...
  sleep 2
  wget -O chromium-${VERSION}.tar.bz2 http://gsdview.appspot.com/chromium-browser-official/chromium-${VERSION}.tar.bz2
fi

echo Running chromium.SlackBuild...
sleep 2
source chromium.SlackBuild
